# -*- coding: utf-8 -*-
"""Função: processar_vendas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1__eqG20E2MqT6TfFIz9_J69MIG2rYIXR
"""

# Esta função deve calcular o total de uma compra, aplicando descontos progressivos e validando o estoque.
def processar_vendas():
  total_compra = 0.0
  itens_comprados = 0

  quantidade_produtos = int(input("Quantos produtos diferentes foram comprados ? "))
  print()
  print("-" *80)
  for i in range(1, quantidade_produtos + 1):
    nome = input("Nome do produto: ")
    preço = float(input("Preço unitário: "))
    qtd = int(input("Quantidade deste produto: "))
    print("-" *80)
  if preço <= 0 or qtd <= 0:
     print("Erro: Valores inválidos para ", nome)
  else:
    subtotal = preço * qtd
    total_compra += subtotal
    itens_comprados += qtd
  print()
  if total_compra > 500.00:
    total_final = total_compra * 0.90
    print("Desconto aplicado de 10%! ")
  elif total_compra > 200.00:
    total_final = total_compra * 0.95
    print("Desnconto aplicado de 5%! ")
  else:
    total_final = total_compra
  print("Resumo")
  print()
  print(itens_comprados, "itens")
  print()
  print("Total em R$:", total_final)


processar_vendas()