# -*- coding: utf-8 -*-
"""Função: processar_vendas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1__eqG20E2MqT6TfFIz9_J69MIG2rYIXR
"""

# Esta função deve calcular o total de uma compra, aplicando descontos progressivos e validando o estoque.
def processar_vendas():
  total_compra = 0.0
  itens_comprados = 0

  quantidade_produtos = int(input("Quantos produtos diferentes foram comprados ? "))
  print()
  print("-" *80)
  for i in range(1, quantidade_produtos + 1):
    nome = input("Nome do produto: ")
    preço = float(input("Preço unitário: "))
    qtd = int(input("Quantidade deste produto: "))
    print("-" *80)
  if preço <= 0 or qtd <= 0:
     print("Erro: Valores inválidos para ", nome)
  else:
    subtotal = preço * qtd
    total_compra += subtotal
    itens_comprados += qtd
  print()
  if total_compra > 500.00:
    total_final = total_compra * 0.90
    print("Desconto aplicado de 10%! ")
  elif total_compra > 200.00:
    total_final = total_compra * 0.95
    print("Desnconto aplicado de 5%! ")
  else:
    total_final = total_compra
  print("Resumo")
  print()
  print(itens_comprados, "itens")
  print()
  print("Total em R$:", total_final)


processar_vendas()

def analisar_clima():
  soma_temperaturas = 0.0
  dias_quentes = 0
  alerta_extremo = False

  for dia in range(1,8):
    temp = float(input(f"Digite a temperatura do dia {dia}: "))
    soma_temperaturas += temp
    if temp > 35.0:
      dias_quentes += 1
      if temp > 45.0 or temp > -5.0:
        alerta_extremo = True
  media =  soma_temperaturas / 7
  print("Média semanal: ", media)
  print("-" *65)
  print("Dias acima de 35ºC: ", dias_quentes)
  print("-" *65)
  if alerta_extremo == True:
    print("Cuidado: Condições cliáticas perigosas detectadas!")
  else:
    print("Clima dentro da normalidade operacional")

analisar_clima()

def sistema_turma():
  total_alunos = int(input("Quantos alunos existem na turma ? "))
  print("Um total de:", total_alunos,"alunos")

  for j in range(1,total_alunos + 1):
    nome = input("Nome no aluno: ")
    nota_1 = int(input("Nota 1 do aluno: "))
    nota_2 = int(input("Nota 2 do aluno: "))
    media_aluno = (nota_1 + nota_2) / 2
    print("-" *65)
    if media_aluno >= 7.0:
     print(nome,":Aprovado com média",media_aluno)
    elif media_aluno >= 5.0:
     print(nome,":Recuperação, Média:",media_aluno)
    else:
     print(nome, ":Reprovado")

sistema_turma()

def simulador_popança():
  inicial = int(input("Valor inicial do investimento: R$"))
  taxa = int(input("Taxa de juros mesal:"))
  print(taxa,"%")
  mes = int(input("Número de meses da simulação:"))
  print("-" *65)

  for m in range(1, mes + 1):
    aporte = int(input(f"Quanto deseja depositar por mês? {m} (0 para nenhum): "))

    inicial += aporte
    juros = inicial * (taxa / 100)
    inicial += juros

    print(f"Mês {m} :Saldo atualizado = R$",inicial)
    print("-" *65)


    if inicial > 10000.0:
      print("Parabéns! Você atingiu a meta de 10k no mês",{m})
      print("Resultado final após", mes,"meses:R$",inicial)





simulador_popança()