# -*- coding: utf-8 -*-
"""simulador_popança

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1csRlwYvpunOkXMXXWPOAHx8dzu6z1YVO
"""

def simulador_popança():
  inicial = int(input("Valor inicial do investimento: R$"))
  taxa = int(input("Taxa de juros mesal:"))
  print(taxa,"%")
  mes = int(input("Número de meses da simulação:"))
  print("-" *65)

  for m in range(1, mes + 1):
    aporte = int(input(f"Quanto deseja depositar por mês? {m} (0 para nenhum): "))

    inicial += aporte
    juros = inicial * (taxa / 100)
    inicial += juros

    print(f"Mês {m} :Saldo atualizado = R$",inicial)
    print("-" *65)


    if inicial > 10000.0:
      print("Parabéns! Você atingiu a meta de 10k no mês",{m})
      print("Resultado final após", mes,"meses:R$",inicial)





simulador_popança()