# -*- coding: utf-8 -*-
"""analisar_clima

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGEVJGkh3_Qy90tdeKxFVgDq93OHZezg
"""

def analisar_clima():
  soma_temperaturas = 0.0
  dias_quentes = 0
  alerta_extremo = False

  for dia in range(1,8):
    temp = float(input(f"Digite a temperatura do dia {dia}: "))
    soma_temperaturas += temp
    if temp > 35.0:
      dias_quentes += 1
      if temp > 45.0 or temp > -5.0:
        alerta_extremo = True
  media =  soma_temperaturas / 7
  print("Média semanal: ", media)
  print("-" *65)
  print("Dias acima de 35ºC: ", dias_quentes)
  print("-" *65)
  if alerta_extremo == True:
    print("Cuidado: Condições cliáticas perigosas detectadas!")
  else:
    print("Clima dentro da normalidade operacional")

analisar_clima()