# -*- coding: utf-8 -*-
"""emoji

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mD20LdzQt-ojHt-Oatjka9smW6j1IMzx
"""

import matplotlib.pyplot as plt

emoji_data = {
  "nome": "Smile",
  "grade": [
    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],
    [(255,255,0), (0,0,0),  (255,255,0), (0,0,0),  (255,255,0)],
    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],
    [(255,255,0), (0,0,0),  (0,0,0),  (0,0,0),  (255,255,0)],
    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)]
  ]
}

emoji_processado = {}

for chave, valor in emoji_data.items():
  if chave == "grade":
    nova_grade = []

    for linha in valor:
      nova_linha = []

      for pixel in linha:
        if pixel == (255, 255, 0):
          pixel = (
            int(pixel[0] / 2),
            int(pixel[1] / 2),
            int(pixel[2] / 2)
          )
        nova_linha.append(pixel)

      nova_grade.append(nova_linha)

    emoji_processado[chave] = nova_grade
  else:
    emoji_processado[chave] = valor

print(f"Emoji: {emoji_processado['nome']}")
for linha in emoji_processado["grade"]:
  print(linha)

# MOSTRAR O PROCESSADO (correto)
plt.imshow(emoji_processado["grade"])
plt.axis('off')
plt.show()