# -*- coding: utf-8 -*-
"""sistema_turma

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h-0UwbfNTL6MbJkEq_y4UlcV4WCAf448
"""

def sistema_turma():
  total_alunos = int(input("Quantos alunos existem na turma ? "))
  print("Um total de:", total_alunos,"alunos")

  for j in range(1,total_alunos + 1):
    nome = input("Nome no aluno: ")
    nota_1 = int(input("Nota 1 do aluno: "))
    nota_2 = int(input("Nota 2 do aluno: "))
    media_aluno = (nota_1 + nota_2) / 2
    print("-" *65)
    if media_aluno >= 7.0:
     print(nome,":Aprovado com média",media_aluno)
    elif media_aluno >= 5.0:
     print(nome,":Recuperação, Média:",media_aluno)
    else:
     print(nome, ":Reprovado")

sistema_turma()